@extends('frontend.layout')
@section('body')
    <section>
        <div class="container mt-5">
            <div class="row">
                <div class="col-3">
                    <div class="logo mt-5">
                        <a class="text-white" {{config('app.url')}}"><img src="{{ asset('img/logo.png') }}" alt="greencontributor" class="img-fluid">GreenContributor</a>
                    </div>
                </div>
                <div class="col-9 md-12">
                    <h2><b>PRIVACY POLICY</b></h2><br>
                    <p>
                    By signing up for Greencontributor programs and website, you acknowledge that you accept and consent to the practices and policies outlined in this Privacy Policy. Remember that your use of Greencontributor website and participation in our programs online is at all times subject to the Terms of Service, which incorporates this Privacy Policy.  For the entire current Greencontributor Terms of Service, please click here.<br><br>

                    This Privacy Policy explains how Greencontrbutor collects and uses information from its users.  This policy does not apply to websites or the practices of companies that Greencontrbutor does not own or control, or to individuals that Greencontrbutor does not employ or manage, such as the third parties who publish their content via the Forum.<br><br>

                    If you are younger than 18 years, you may only use Greencontributor, including but not limited to engagement in any associated Greencontrbutor activities, and disclose information to us with your parent’s or guardian’s or teacher's/chaperon's express consent. Please note that any student can only register after approval from their teacher or parent or legal guardian. Review this Privacy Policy with your teacher and parent or guardian and make sure you understand it.<br><br>

                    If we learn we have collected personal information from a youth participant under the relevant age without parental consent, or if we learn a youth participant under the relevant age has provided us personal information beyond what we request from him or her, we will delete that information as quickly as possible. If you believe that a youth participant under the relevant age may have provided us personal information in violation of this paragraph, please contact us at greencontributor.org.<br><br>

                    We receive and store any information you knowingly enter within your profile or post on the Forum, whether via computer, mobile phone, other wireless device, or that you provide to us in any other way.  The only personal Information we require is your name as in passport or government approved document, age, username, email, teachers name & Teacher code generated by Greencontributor and parent’s email  for registration in the program. Through the functionality of the website, you may choose to populate your user profile on the Greencontributor website with personal information, including, without limitation, username, physical location, photograph, Instagram handle, and a personal written description. Please note that this can only be uploaded with the consent of your parent or teacher and we will send an email to the parent & teacher mentioning about your registration in our program.  We receive and store information that is entered in your user profile on both Greencontributor server and Google Drive.<br><br>

                    This user profile information will be displayed to other Greencontributor members or partners to facilitate user interaction within the website or facilitate interaction with Greencontributor and participating partners or collaborating schools.  Please keep in mind that information (whether personal information or not) or content that you voluntarily disclose online (in your user profile, to your connections, in comments to our Forum, etc.) becomes available to other users and can be collected and may be used by others. Any images, captions or other content that you submit to the website in a manner any other user can view may be redistributed through the Internet and other media channels. For example,the content you contribute in your user profile will be displayed to other members of Greencontributor or its partners or collaborating schools; we cannot, however, control what they will do with such content after you have disclosed it. We will only use your email address or any approved social media sites we use to communicate between members to send you notifications and communicate with you about Greencontributor programs. If you no longer wish to receive any messages or emails from Greencontributor, please contact us at greencontributor.org.<br><br>

                    We receive and store certain types of usage information whenever you interact with our website. For example, Greencontributor automatically receives and records information on our server logs from your browser, including your IP address, Wayfinder Society cookie information, and the page(s) you requested. We also record the details of your activity on the website, and the number and frequency of visitors to our site and its components.

                    Your Greencontributor account is protected by a password for your privacy and security.  You may help protect against unauthorized access to your account by selecting and protecting your password appropriately and limiting access to your computer and browser by signing off after you have finished accessing your account.

                    Greencontributor endeavors to keep your information private; however, we cannot guarantee security. Unauthorized entry or use, hardware or software failure, and other factors may compromise the security of user information.

                    The Services contain links to other sites. We are not responsible for the privacy policies and/or practices on other sites (but you should read all third parties’ privacy policies to ensure you understand them). This Privacy Policy only governs information collected by Greencontributor on the website.

                    If you would like to request that your child’s personal information be updated or deleted, or if you’d like to refuse further contact of your child (or, if you are a teacher, a child that is in your class) by Greencontributor, please contact us at greencontributor.org

                    Greencontributor reserves the right to withdraw or change the content of the site and Privacy Policy at any time without notifying you and without having any legal responsibility towards you.
                    </p>
                </div>
            </div>
        </div>
    </section>
    @include('frontend.components.footer')
@endsection

